name: learn-github-actions
on: [push]
jobs:
  create-build-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - run: npm run export
